### ISSUE TITLE
Could you consider our cvpr 2023 paper about video generation with diffusion models?

### ISSUE THREAD

**Issue by nihaomiao** [YangLing0818/Diffusion-Models-Papers-Survey-Taxonomy#4]
Hi, @YangLing0818,

Thanks very much for your efforts in collecting these excellent works! I am wondering whether you can consider our latest cvpr 2023 paper, which applies diffusion models to generate optical flow to achieve image-to-video generation.
Title: Conditional Image-to-Video Generation with Latent Flow Diffusion Models.
Paper Link: https://arxiv.org/pdf/2303.13744.pdf
Code Link: https://github.com/nihaomiao/CVPR23_LFDM

Thanks a lot!
Haomiao Ni

**Comment by YangLing0818** [comment]
> Hi, @YangLing0818,
> 
> Thanks very much for your efforts in collecting these excellent works! I am wondering whether you can consider our latest cvpr 2023 paper, which applies diffusion models to generate optical flow to achieve image-to-video generation. Title: Conditional Image-to-Video Generation with Latent Flow Diffusion Models. Paper Link: https://arxiv.org/pdf/2303.13744.pdf Code Link: https://github.com/nihaomiao/CVPR23_LFDM
> 
> Thanks a lot! Haomiao Ni

Hi,

Thanks for your attention on our survey paper, we have added your paper, please check.

Best.

**Comment by nihaomiao** [comment]
Sounds great! Thank you so much for your interest! I am also looking forward to the final version of your survey paper!

Bests
