### ISSUE TITLE
Supplement graph generation paper

### ISSUE THREAD

**Issue by GRAPH-0** [YangLing0818/Diffusion-Models-Papers-Survey-Taxonomy#6]
Hi @YangLing0818 ,
 
Thanks for your wonderful survey!
Would you mind supplementing our paper published in ICDM 2022 in `3.2 Data with Invariant Structures`? It is also an early work applying diffusion models to permutation invariant graph generation.
Title: GraphGDP: Generative Diffusion Processes for Permutation Invariant Graph Generation
Paper link: https://arxiv.org/abs/2212.01842
Code link: https://github.com/GRAPH-0/GraphGDP

BTW, our latest paper is also related to `6. Molecular Graph Modeling`, not sure if you are stll considering adding papers.
Title: Learning Joint 2D & 3D Diffusion Models for Complete Molecule Generation
Paper link: https://arxiv.org/abs/2305.12347
Code link: https://github.com/GRAPH-0/JODO  

Thanks a lot!
Han Huang

**Comment by YangLing0818** [comment]
> Hi @YangLing0818 ,
> 
> Thanks for your wonderful survey! Would you mind supplementing our paper published in ICDM 2022 in `3.2 Data with Invariant Structures`? It is also an early work applying diffusion models to permutation invariant graph generation. Title: GraphGDP: Generative Diffusion Processes for Permutation Invariant Graph Generation Paper link: https://arxiv.org/abs/2212.01842 Code link: https://github.com/GRAPH-0/GraphGDP
> 
> BTW, our latest paper is also related to `6. Molecular Graph Modeling`, not sure if you are stll considering adding papers. Title: Learning Joint 2D & 3D Diffusion Models for Complete Molecule Generation Paper link: https://arxiv.org/abs/2305.12347 Code link: https://github.com/GRAPH-0/JODO
> 
> Thanks a lot! Han Huang

Hi,

Thanks for your attention on our survey paper, we have added your papers, please check.

Best.

**Comment by GRAPH-0** [comment]
Thanks for your quick edit!
